kde_model:
  num_bins: 11
  sigma: 0.1
patch_model:
  conv_input_channel: 3
  conv_output_channel: 16
  block1_output_channel: 32
  block1_num_layer: 1
  block2_output_channel: 64
  block2_num_layer: 1
  block3_output_channel: 128
  block3_num_layer: 1
  flatten_size: 8192
  num_features: 16
image_generation_model:
  linear_size: 8192
  reshape_size: [128, 8, 8]
  block1_output_channel: 128
  block1_num_layer: 1
  block2_output_channel: 64
  block2_num_layer: 1
  block3_output_channel: 32
  block3_num_layer: 1
  output_channel: 3
classification_model:
  fc1_output_size: 384
  fc2_output_size: 192
  dropout_rate: 0.25
  num_classes: 2