defaults:
  - _self_
  - model: mnist_ucc.yaml
  - experiment: null
args:
  model_path: saved_models/mnist_ucc_best.pth
  num_instances: 32
  ucc_start: 1
  ucc_end: 4
  batch_size: 20
  num_workers: 4
  num_bins: 11
  num_features: 10
  seed: 22